### ISSUE TITLE
Error serializing TimeSpan.Zero

### ISSUE THREAD

**Issue by aluxnimm** [ical-org/ical.net#104]
The TimeSpanSerializer doesn't correctly serialize 0.
This is needed for alarm triggers at event start time for example which, should look like
`TRIGGER:P0D`
Instead the Serializer only generates:
`TRIGGER:P`

Bug was also already present in DDay.iCal

**Comment by kdaveid** [comment]
Hi Alex, please reference your request to the specific part in the RFC 5545 spec. I can not find the default null value description for duration (3.3.6 in [RFC5545](http://www.ietf.org/rfc/rfc5545.txt)).

**Comment by aluxnimm** [comment]
`dur-value  = (["+"] / "-") "P" (dur-date / dur-time / dur-week)`

And every possible value has 
`1*DIGIT`

Thats why it can't be just P but P0D

**Comment by rianjs** [comment]
I wonder if `TimeSpanSerializer.SerializeToString` can be delegated to NodaTime, which supports ISO-8601 formatting OOTB:

http://nodatime.org/1.2.x/userguide/period-patterns.html

For some reason, an ISO-8601 `TimeSpan.ToString("o")` isn't a thing, which is weird, because I'd expect the date and time types to be symmetrical where possible.

**Comment by aluxnimm** [comment]
it's not exactly ISO-8601

> Note that unlike
>       [ISO.8601.2004], this value type doesn't support the "Y" and "M"
>       designators to specify durations in terms of years and months.

**Comment by rianjs** [comment]
Fixed in a12a089731abd846576780ced1d82b4cd1763de6

Available in nuget version 2.2.10
