### ISSUE TITLE
Events with the same UID are not treated as a single event when computing recurrence values

### ISSUE THREAD

**Issue by robertsuditu** [ical-org/ical.net#120]
Hi, I have this calendar:

BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Calendar 2
X-WR-TIMEZONE:Europe/Bucharest
BEGIN:VTIMEZONE
TZID:Europe/Bucharest
X-LIC-LOCATION:Europe/Bucharest
BEGIN:DAYLIGHT
TZOFFSETFROM:+0200
TZOFFSETTO:+0300
TZNAME:EEST
DTSTART:19700329T030000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0300
TZOFFSETTO:+0200
TZNAME:EET
DTSTART:19701025T040000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Europe/Bucharest:20160620T063000
DTEND;TZID=Europe/Bucharest:20160620T113000
RRULE:FREQ=DAILY;UNTIL=20160621T205959Z
EXDATE;TZID=Europe/Bucharest:20160620T063000
EXDATE;TZID=Europe/Bucharest:20160621T063000
DTSTAMP:20160901T104339Z
UID:5r6bvmv78cspcrgps92dc6mtm0@google.com
CREATED:20160622T153613Z
DESCRIPTION:
LAST-MODIFIED:20160622T154217Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Europe/Bucharest:20160829T110000
DTEND;TZID=Europe/Bucharest:20160829T163000
RRULE:FREQ=DAILY
DTSTAMP:20160901T104339Z
UID:gknfcr66sb7rpangtprsthmpn8@google.com
CREATED:20160901T104300Z
DESCRIPTION:
LAST-MODIFIED:20160901T104311Z
LOCATION:
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:testRScuAD
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Europe/Bucharest:20160901T163000
DTEND;TZID=Europe/Bucharest:20160901T220000
DTSTAMP:20160901T104339Z
UID:gknfcr66sb7rpangtprsthmpn8@google.com
RECURRENCE-ID;TZID=Europe/Bucharest:20160901T110000
CREATED:20160901T104300Z
DESCRIPTION:
LAST-MODIFIED:20160901T104314Z
LOCATION:
SEQUENCE:2
STATUS:CONFIRMED
SUMMARY:testRScuAD
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Europe/Bucharest:20160903T070000
DTEND;TZID=Europe/Bucharest:20160903T123000
DTSTAMP:20160901T104339Z
UID:gknfcr66sb7rpangtprsthmpn8@google.com
RECURRENCE-ID;TZID=Europe/Bucharest:20160903T110000
CREATED:20160901T104300Z
DESCRIPTION:
LAST-MODIFIED:20160901T104315Z
LOCATION:
SEQUENCE:2
STATUS:CONFIRMED
SUMMARY:testRScuAD
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

**GetOccurrences** gives two extra occurrences (for the 1st of September and 3rd of September) unlike Google and Outlook that correctly gets the occurrences. So it does not know to EXCEPT the normal occurrences for these two days (mentioned above). It must take into consideration the Recurrence ID and deduce that those two days are exceptions from the recurrence rule. I hope I'm clear enough :)

**Comment by rianjs** [comment]
Are you using the latest version I published 8 hours ago? It fixed a bunch of recurrence bugs.

**Comment by robertsuditu** [comment]
Yup. The same problem. You imported the calendar I mentioned above? Don't you see the problem? I can also send you a screenshot with the problem if it helps.

**Comment by rianjs** [comment]
No, I'm on mobile at the moment. I'll have a look at it sometime this week hopefully. Just making sure I'm not wasting my time chasing bugs that're already fixed is all. ;)

**Comment by robertsuditu** [comment]
Ok, please let me know if you want more details on this. Also, can we have the Remove method for PeriodList? It's useful when removing exceptions, recurrent dates, etc.

**Comment by rianjs** [comment]
> Also, can we have the Remove method for PeriodList? It's useful when removing exceptions, recurrent dates, etc.

Oh, hmm. Can you open a separate issue for that? I like keeping my commits/pull requests focused on single issues.

**Comment by rianjs** [comment]
Your ical paste has 4 VEVENTs in it. Reading and understanding each one takes 3-5 minutes. So that means it takes me 20 minutes to read your bug report. That's a low-value use of time when I have many other tickets I could look at.

Could you narrow it down a bit? Which VEVENT instances are misbehaving? I see that there are two distinct events. The second one appears to have 3 edits associated with it(?).

**Comment by rianjs** [comment]
OK, I think I see what's happening.
- You have an event that specifies a start (Aug 29 @ 11:00) and an end (16:30) and recurrence rule (Daily). Its UID is `gknfcr66sb7rpangtprsthmpn8@google.com`, Sequence = 1
- This event is modified (Sequence = 2), specifying a start time of 16:30 and an end of 22:00 for Sept 1. Same UID.
- The event is modified again (still Sequence = 2), specifying a start time of 07:00 and end time of 12:30 for Sept 3.

When computing the recurrence set, Outlook and Google Calendar effectively interpret this as excluding the Sept 1 and 3 dates from the initial recurrence set (treating them like EXDATEs) and evaluating the Sept 1 and 3 overrides, almost like they're RDATEs. The way this is done is by combining all the same UIDs together, and pretending they're a single event when computing the recurrence set.

ical.net considers recurrences as being associated with a single VEVENT. Having a `Calendar`-level function that squashes all component `Uid`s together to consider as an ordered bundle when computing recurrences doesn't exist in the current data model. So that's problem with the data model itself. _sigh_

There isn't going to be an easy or quick fix, but it should get easier when the type interdependencies are reduced, and the service provider pattern is retired. I'm going to tag this as v3, since it's such a significant undertaking.

**Comment by rianjs** [comment]
I've added a unit test that should be turned on for v3.

I think the API should look something like this:

``` csharp
var calendar = Calendar.LoadFromStream(new StringReader(ical)).First();

var startSearch = DateTime.Parse("2016-08-01T00:00:00");
var endSearch = startSearch.AddDays(45);

var occurrences = calendar.GetOccurrences(string componentUid, DateTime startSearch, DateTime endSearch);
```

**Comment by robertsuditu** [comment]
Yes, Rian, you've got the point, thank you!

**Comment by rianjs** [comment]
Eh, the fix is fairly straightforward, actually. Maybe.

``` csharp
public HashSet<Occurrence> GetOccurrences(string uid, DateTime searchStart, DateTime searchEnd)
{
    var events = calendar.Events
        .Where(e => e.Uid.Equals(someId, StringComparison.Ordinal))
        .OrderBy(e => e.Sequence)
        .ThenBy(e => e.DtStamp)
        .ThenBy(e => e.Start);

    var occurrences = events.First().GetOccurrences(startTime, endTime);
    foreach (var e in events.Skip(1))
    {
        var subset = e.GetOccurrences(startTime, endTime);
        //Figure out the dates that overlap
        //Subtract the Occurrences from the initial set where there's overlap, if any
        occurrences.UnionWith(subset);
    }
    return occurrences;
}
```

I'm sure the devil is in the details.

**Comment by minichma** [comment]
See #659
