### ISSUE TITLE
Bug: Start time of 00:00:00 creates wrong end time/period

### ISSUE THREAD

**Issue by MartinRothschink** [ical-org/ical.net#146]
I'm using this ICS:

BEGIN:VEVENT
DTEND;TZID=W. Europe Standard Time:20160101T050000
DTSTAMP:20160928T145431Z
DTSTART;TZID=W. Europe Standard Time:20160101T000000
RRULE:FREQ=DAILY
UID:c24f7c04-fe82-4193-bef0-ebbda857a904
END:VEVENT

And get an Occurence.Period.EndTime of 00:00:00 next day, i.e. the period is 1 day instead of 5h.

If I change the start time to 00:00:01
DTSTART;TZID=W. Europe Standard Time:20160101T00000**1**
everything is correct.

Using 2.2.14

**Comment by MartinRothschink** [comment]
Here is a unit test:

``` csharp
[Test]
public void PeriodShouldBeFiveHours()
{
    const string ical =
@"BEGIN:VCALENDAR
PRODID:-//AxoNet Software GmbH//NONSGML Lights-Out//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
TZNAME:W. Europe Standard Time
TZOFFSETTO:+0100
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYDAY=SU;BYMONTH=10;BYSETPOS=-1;WKST=MO
DTSTART:16010101T030000
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:00010101T020000
RRULE:FREQ=YEARLY;BYDAY=SU;BYMONTH=3;BYSETPOS=-1;WKST=MO
TZNAME:W. Europe Daylight Time
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
BACKGROUND:BUSY
DTEND;TZID=W. Europe Standard Time:20160101T050000
DTSTAMP:20160928T145431Z
DTSTART;TZID=W. Europe Standard Time:20160101T000000
RESOURCES:computer
RESOURCES:S-1-5-21-419640081-1541041111-925700815-10658
RRULE:FREQ=DAILY
SUMMARY:WIN7X64
UID:c24f7c04-fe82-4193-bef0-ebbda857a904
X-LIGHTSOUT-ACTION:START=DoNothing\;END=Reboot\,Force\,AfterBackup
X-LIGHTSOUT-MODE:TimeSpan
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
END:VEVENT
END:VCALENDAR
";

    var collection = Calendar.LoadFromStream(new StringReader(ical));
    var checkAgainst = new DateTime(2016, 1, 1);
    var occurrences = collection.GetOccurrences<Event>(checkAgainst);

    var expectedPeriodHours = 5.0;
    var receivedPeriod = occurrences.First().Period.Duration.TotalHours;

    Assert.IsTrue(expectedPeriodHours.Equals(receivedPeriod));
}
```

**Comment by rianjs** [comment]
Thanks for the unit test. @MartinRothschink - do you think this is the same as as #77?

(I still haven't come up with a good way of telling "midnight" apart from "date without a time".)

**Comment by michaelmcneilnet** [comment]
For anyone else coming across this, I found the answer in #77.

```
var e = new Event
{
    DtStart = new CalDateTime(myDateTimeAtMidnight)
    {
        HasTime = true
    }.
    Duration = myDuration,
}
```

By setting the flag to true, you are telling the library that you have explicitly set the time to midnight, rather than it having defaulted to midnight because you haven't set a time.

**Comment by ghost** [comment]
I've run across this today and there's an additional wrinkle that appears if you have a recurrence with a start time at midnight and a zero duration. HasTime doesn't fix it (though making a duration does). RFC5545 says:

```
For cases where a "VEVENT" calendar component specifies a "DTSTART" property
with a DATE value type but no "DTEND" nor "DURATION" property, the event's 
duration is taken to be one day.  For cases where a "VEVENT" calendar component 
specifies a "DTSTART" property with a DATE-TIME value type but no      
"DTEND" property, the event ends on the same calendar date and time of day 
specified by the "DTSTART" property.
```

So if I understand right, if you have a date and time specified and a zero duration, enddatetime == startdatetime.

I created an every-four-hour hourly recurrence event specifying `HasTime` with the start date 1-Jan-18 00:00:00. Both `startTime` and `endTime` set  `HasTime = true`, just to be safe:

```
           var pattern = new RecurrencePattern(FrequencyType.Hourly, 4);
           var startTime = new CalDateTime(2018, 1, 1, 0, 0, 0) { HasTime = true };
           var endTime = new CalDateTime(2018, 1, 2, 0, 0, 0) { HasTime = true };

           var calendarEvent = new CalendarEvent  {  Start = startTime  };
           calendarEvent.RecurrenceRules.Add(pattern);

            var events = new List<CalendarEvent> { calendarEvent  };
            var calendar = new Calendar();
            calendar.Events.AddRange(events);
```

If I understand the code correctly, this should generate occurrences at 00:00, 04:00, 08:00, 12:00, 16:00 and 20:00, a total of six. However, it only generates five - the 00:00 occurrence is not created.

It turns out that the code that calculates candidate occurrences DOES create the 1-Jan-18 00:00 occurrence, but it disappears because of an interaction between `EventEvaluator.Evaluate`, `Period.Duration.get` and the recurrence filtering code. `EventEvaluator.Evaluate` calculates the end time of the periods generated like so:

```
            foreach (var period in Periods)
            {
                period.Duration = CalendarEvent.Duration;
                period.EndTime = period.Duration == null
                    ? period.StartTime
                    : period.StartTime.Add(CalendarEvent.Duration);
            }
```

Because I declared no duration on my event, `CalendarEvent.Duration` is a `TimeSpan(0)`. But  after the assignment, `Period.Duration` on the 1-Jan-18 00:00 period reports the duration as 1 day, because `Period.Duration.get` does this:

```
           get
            {
                if (StartTime != null
                    && EndTime == null
                    && StartTime.Value.TimeOfDay == TimeSpan.Zero)
                {
                    return TimeSpan.FromDays(1);
                }
                return _duration;
            }
```

Since our `StartTime` *is not* null and our `EndTime` *is* null, and because midnight parses as TimeSpan.Zero, we don't return the zero-length _duration that was assigned in `Period.Duration.set`; instead we return one day. 

The code in `EventEvaluator` does set the `EndTime`, but it sets it to `period.StartTime.Add(CalendarEvent.Duration)` - note that's *`CalendarEvent.Duration`*, or zero. So we end up with a Period whose StartTime is 1-Jan-18 00:00:00 and whose end time is 1-Jan-18 00:00:00, but whose duration is reported as one day!

This interacts badly with recurrence logic filtering later on (I haven't pinpointed exactly where, but I bet it is somewhere having to do with overlapping occurrences), and the event occurrence ends up getting removed; you end up with five occurrences rather than six.

 I have a work around by setting my `Duration` for my `CalendarEvent` to `TimeSpan(1L)`, one tick. But now we have two tricks (use `HasTime`; use `Duration = new TimeSpan(1L)`) to fix the problem of midnight = zero without duration.  I've just started looking at this code so I have no suggestions on how to clean this up, sorry. I thought it would be good to show another place where it is an issue though. I can write up unit tests that show the behavior if that would be of help.
