### ISSUE TITLE
Allow Serializing DataTypes

### ISSUE THREAD

**Issue by gilmishal** [ical-org/ical.net#211]
I am not sure this is the best heading for the question - but I need some way to serialize an Event which isn't a perfect .ics file.

the datatype I am trying to serialize is similar to [Google's Calendar API ](https://developers.google.com/google-apps/calendar/recurringevents) Since I didn't see dynamically serializing `DataType`s  supported out of the box - After reading some of your code I used the following Hack:

    var vEvent = new Event();
    foreach (var str in strArr)
    {
          var lexer = new iCalLexer(new StringReader(str));
          iCalParser prs = new iCalParser(lexer);
          var property = prs.property(Ical.Net.Serialization.SerializationContext.Default, vEvent );
    }

it works with the following inputs:  `"EXDATE;VALUE=DATE:20150610"` and `"RDATE;VALUE=DATE:20150609,20150611"`

however the following input: `"RRULE:FREQ=DAILY;UNTIL=20150628;INTERVAL=3"` throws an `IndexOutOfRangeException` in `RecurrencePatternSerializer.Deseralize()`.
That being said- using the same input with `RecurrencePatternSerializer` directly - works as expected.

The question is - is there another way to leverage your deserialization without checking the DataType? I am sure you are doing that behind the scenes - so doing it myself with be a waste.

If this is the best way - why am I getting the `IndexOutOfRangeException`? Am I missing something?

I am using the latest nuget version.

**Comment by gilmishal** [comment]
for some reason - `iCalParser.value()` returns `"RRULE:FREQ=DAILY;UNTIL=20150628;INTERVAL"` for the given input. This causes the `IndexOutOfRangeException` in `Ical.Net.Serialization.iCalendar.Serializers.DataTypes.RecurrencePatternSerializer.Deserialize(TextReader tr) in C:\Users\Gil\Downloads\ical.net-master\ical.net-master\v2\ical.net\Serialization\iCalendar\Serializers\DataTypes\RecurrencePatternSerializer.cs:line 243`

**Comment by gilmishal** [comment]
Sending `"RRULE:FREQ=DAILY;UNTIL=20150628;INTERVAL=3  "` fixes the issue. I am currently adding spaces to my strings to overcome this bug/feature

**Comment by rianjs** [comment]
The parser should be `internal`, but instead it's `public`. Changing it would be a breaking change, so I've left it as-is. I make no guarantees about how it behaves, or what bugs you might find using it outside the standard serialize-deserialize round-trip workflows.

The fact that you even went looking for the parser internals speaks to a weakness of the API: there's no way to serialize arbitrary calendar components. In a perfect world you could do `CalDateTime.ToString()` or `Event.ToString()`, and you'd get back the serialized sub-component. Similarly, you should be able to hand a serialized VEVENT to the `Event` constructor, and get back an `Event` component. Alas, this is not the case... internally, ical.net uses the service provider pattern, which is inherited from its dday.ical forbears. I'd really like to change that, but time/energy/interest hasn't aligned lately for me to dive into that, because it'd be quite a lot of hard work, I suspect. It IS on the docket for v3, but again, v3 doesn't have a timeframe attached to it, but you may want to read about it nonetheless:

http://rianjs.net/2016/07/api-changes-for-ical-net-v3

**Comment by gilmishal** [comment]
I kinda figured it wasn't meant to be public, but I needed the feature... I do think the API should allow serializing and deseralizing arbitrary calendar components, but I can understand your lack of time. I am starting to use your library for my startup, so I might actually work on your library a bit to fit my needs in the future, I can't promise anything yet, but I wouldn't mind contributing on this feature when the time comes... maybe even .net core support

**Comment by rianjs** [comment]
That's actually [how I ended up adopting dday.ical and renaming it](http://rianjs.net/2016/07/dday-ical-is-now-ical-net): we were using it at work, and the performance & accuracy wasn't good enough.

> maybe even .net core support

I intend to spend some time on this, as soon as VS2017 drops and the dust has settled WRT back-to-msbuild-instead-of-project.json. With .NET everywhere being a real thing, there's just too much potential value to ignore Core.
