### ISSUE TITLE
Reflow DDay.ICal Nuget Package To ICal.Net

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ical-org/ical.net#26]
I will reflow the Nuget package as soon as the infinite redirect loop is solved on https://nuget.org. I'd much prefer people are lead to your package, and I believe the stats will jump over too. So it will make ICal.Net more relevant, but don't quote me on it :)

**Comment by khalidabuhakmeh** [comment]
Hey @rianjs 

I was thinking it may be better to rebrand the current package that exists on Nuget.org rather than publishing a new package entirely. I made you an owner of the existing one and you can modify the nuspec entirely to match yours now.

Advantages:
- Retain statistics
- Retain users
- Give community an easier way to find you.

Apparently, there is no **reflow** function, it was a feature that was never implemented on Nuget.org even though the link was there.

Thoughts?

**Comment by rianjs** [comment]
That sounds reasonable. Give me a day or three to look into the details of how that would work with respect to, e.g., renaming the package. I'm sure there's a bunch of `packages.config` files floating around referencing `dday.ical`.

**Comment by khalidabuhakmeh** [comment]
Also, have you thought about migrating to `xproj`? I tried the `NetCore` branch on my Mac OS X and I can't build it via `dotnet build`. Seems like I need Visual Studio to build.

**Comment by rianjs** [comment]
I'll get there soon-ish. :)

I hadn't done anything at all with .NET Core before Sunday, so I haven't had time to learn the idiosyncrasies associated with non-csproj .NET projects. I also had no idea what .NET Core was OK with, and what would have to be changed, so I was basically starting with zero knowledge of what the process would look like; I just assumed it could be done.

I knew I wanted to back-port the changes to non-Core .NET for safety reasons: I could run the unit tests to make sure I wasn't writing and then back-porting bugs. This is my thinking WRT order of operations, with progress indicated:
1. ~~Try importing the ANTLR code, see the various and myriad ways in which .NET Core is unhappy. E.g. non-generic collections.~~
2. ~~Delete all the unreferenced code in ANTLR that I can find.~~
3. ~~Port all the non-generic collection usage in ANTLR to generics, back-port the changes to non-Core ANTLR~~
4. ~~Do an easy sweep through the remaining ANTLR code, and refactor some of the stranger idioms, but not spend much time there as it's machine-generated, and I hope to make it go away entirely in v3~~ ([C.f.](http://rianjs.net/2016/07/api-changes-for-ical-net-v3))
5. ~~Copy ANTLR to .NET Core, see what breaks, and back-port the fixes to non-Core ANTLR, making sure nothing breaks in the unit tests.~~
6. ~~Copy ical.net.Collections to .NET Core, see what breaks, back-port fixes~~
7. ~~Move ical.net to .NET Core, see what breaks, back-port fixes.~~
8. Upgrade ical.net.UnitTests to nuget-based nunit 3 (previous versions were committed to the repo, and hard-referenced in the csproj, and get them working (in-progress)
9. Upgrade ical.net.UnitTests to use generics instead of `Hashtable`s and `ArrayList`s so it'll work in a .NET Core world (in-progress)
10. Copy the UnitTests project over to the .NET Core solution, make sure all the unit tests pass
11. Figure out what the .NET Core `xproj` and build idioms are, and make it idiomatic

I did 1-7 on Sunday/Monday. Alas there aren't more holiday weekends immediately on the horizon, so rate of change may slow a bit, but the path forward is very clear and straightforward.

**Comment by khalidabuhakmeh** [comment]
As an update, I was able to build using Xamarin Studio on my Mac.

**Comment by rianjs** [comment]
For historical purposes, here's the dialog between nuget staff and myself:

> **Date:** Tue, Jul 5, 2016 at 2:46 PM
> **Email:** rianjs (rstockbower@gmail.com)
> **Reason:** dday.ical and ical.net package id naming conflict
> 
> **Message:** I recently took over a library (dday.ical) that had been abandoned for quite a while. After tracking down the original creator for his permission, I forked, relicensed, and renamed his library to ical.net. I published a nuget package with that id about a week ago.
> 
> I contacted Khalid Abuhakmeh, who packaged dday.ical here on nuget.org some years ago, asking him to redirect users to my newer package. Instead, he suggested that I just take over the dday.ical package. He made me an owner on dday.ical this morning.
> 
> I tried to take down my ical.net package (which only has a few downloads), so I could rename dday.ical without conflicts. Nonetheless, I'm getting this error, which isn't a huge surprise:
> 
> "The title of your package, 'ical.net', is similar to the ID of an existing package, which can cause confusion with our users. Please modify the title of your package and try uploading again."
> 
> I would like to permanently delete ical.net, so I can rename dday.ical instead. Is this something that is possible?
> 
> Thanks,
> -Rian

**Comment by rianjs** [comment]
> **From:** Xavier Decoster
> **Date:** Tue, Jul 12, 2016 at 3:36 AM
> 
> Hi Rian,
> 
> We typically do not delete packages from nuget.org to avoid breaking consumers.
> I noticed the ical.net package already has 232 total downloads, which indicates changes are high that consumers would be broken by removing the package.
> 
> My suggestion would be to do the following:
> As a package owner of the dday.ical package, you can unlist the dday.ical package versions and upload a new version (make the dday.ical package an empty package) which depends on ical.net.
> Optionally, you can clearly indicate that the dday.ical package is obsolete (e.g. in the package description), and suggest users to install the ical.net package directly instead.
> 
> This avoids the renaming issue and produces the same outcome: people will be using the ical.net package (one way or another).
> Existing users would get the update notification and pull in the new package.
> From then on, you can push updates to the ical.net package, and leave the dday.ical package as-is.
> 
> Best regards,
> Xavier

**Comment by rianjs** [comment]
I'm going to take Xavier's suggested approach:
- Bump the dday.ical major version number to 2
- Change the description to "Obsolete: DDay.iCal / Use ical.net instead"
- Create the empty package, and specify ical.net as a dependency
- Do a little research to see if there's a way to always pull in the latest ical.net

Hopefully I won't have to publish a new dday.ical package every time I increment the major version number...

**Comment by rianjs** [comment]
dday.ical nuget package updated: https://www.nuget.org/packages/DDay.iCal/

**Comment by rianjs** [comment]
b662a0fc786dfd0a44e81b76c508f9b287c984c9
