### ISSUE TITLE
Event status should be uppercase

### ISSUE THREAD

**Issue by Kiitoksia** [ical-org/ical.net#318]
When supplied an iCal with a status of confirmed, the serialised string does not parse correctly.

Input:
`Calendar calendar = new Calendar();
calEvent.Status = Ical.Net.EventStatus.Confirmed;`

Output:

> STATUS:Confirmed

After using various iCal validators, they all fail to parse as Confirmed should be in uppercase.
[https://icalendar.org/iCalendar-RFC-5545/3-8-1-11-status.html](https://icalendar.org/iCalendar-RFC-5545/3-8-1-11-status.html)

Simply doing this before calling the validators, causes it to parse correctly.

>calendarString = calendarString.Replace("STATUS:Confirmed", "STATUS:CONFIRMED");

**Comment by rianjs** [comment]
You are quite right. Looking at the code... it seems this will be a breaking change since `EventStatus` (and the other statuses like `TodoStatus`) are `enum`s, not strings. That's unfortunate.

**Comment by rianjs** [comment]
Even if the API text is unchanged, code will still have to be re-compiled. I.e., it's not binary compatible. If your application expects the old enums, and your DLL has the statuses as string constants... that's bad.

That means bumping the major versions again, for both the existing `v2` and `net-core` (3.x) versions.

I think implementing the fix means discontinuing support for v2 (because it will, [by definition](http://semver.org/), not be v2 anymore), and just continuing with net-core/v3. Hmm. I'll need to think about it some.

**Comment by rianjs** [comment]
Fixed in nuget version 4.0.0: https://www.nuget.org/packages/Ical.Net/4.0.0
