### ISSUE TITLE
Ical.Net dont installing on Net Framework 4.5.1

### ISSUE THREAD

**Issue by maxterehin** [ical-org/ical.net#329]
Hi. I'm try to install Ical.Net package, but i get following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'System.Reflection.TypeExtensions 4.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by rianjs** [comment]
Short answer: Use v2. They have feature-parity, but some of the type names are different. v2 doesn't have more bugs, and it's not slower. In fact, I use v2 in our production environments.

Longer answer: ical.net v3 targets [netstandard 1.3](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), so if you're targeting .NET Framework, you have to target 4.6 or higher in order to use v3.

**Comment by afterlogic-support** [comment]
v2 does not work with .NET 4.5 in debug builds. .NET 4.6 is required. I'm building from the sources. Only release builds are equipped with .NET 4.5 targets. Debugging with a release build is harder. Not critical but having debug targets for .NET 4.5 out-of-box would make life a bit easier.
