### ISSUE TITLE
Deserialization fails on X-APPLE-STRUCTURED-LOCATION

### ISSUE THREAD

**Issue by BillsHead** [ical-org/ical.net#348]
This looks like an Apple bug rather than an ical.net bug, but maybe something you should be able to accommodate anyway.

I'm pulling an ICS feed from an Apple calendar and found that deserialization fails when there are line breaks in the location. The LOCATION property has them correctly escaped, but the X-APPLE-STRUCTURED-LOCATION does not. Here's a sample:
```
BEGIN:VCALENDAR
VERSION:2.0
X-WR-CALNAME:Test Calendar
X-APPLE-CALENDAR-COLOR:#FF9500
X-WR-CALDESC:
BEGIN:VEVENT
CREATED:20171127T114122Z
UID:1EAC2183-9999-9999-9999-9E424DE08712
DTEND;TZID=America/New_York:20171201T150000
SUMMARY:Test Event
DTSTART;TZID=America/New_York:20171201T133000
DTSTAMP:20171127T114211Z
LOCATION:Some Store\n123 Main 
 Street\nSpringfield\, VA 22222 \n703-555-1212
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-MAPKIT-HANDLE=aaaaaaaaaaaaa
 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
 aaaaaaaaaaa;X-APPLE-RADIUS=44.44444444444444;X-TITLE=null:
123 Main Street
Springfield, VA 22222
703-555-1212":geo:11.111111,-11.111111
SEQUENCE:0
END:VEVENT
END:VCALENDAR
```
Since the "123 Main Street" line is not indented, it's not getting parsed as part of the X-APPLE-STRUCTURED-LOCATION, so the parser throws an exception when it hits that line.

**Comment by copernicus365** [comment]
I found a related error, it looks to me like in this case, it's due to one of the properties within the `X-APPLE-STRUCTURED-LOCATION` property not having a double quote char escaped. I don't know if that is an error on Apple's end, or if this is not breaking of the iCal spec and therefore should be handled correctly. The fix would be to alter the regex the library generates, see static function where that regex string is built at: [`SimpleDeserializer.BuildContentLineRegex`](https://github.com/rianjs/ical.net/blob/df5e4e0c402041fb89cb4bb97db3b1582eccdc97/net-core/Ical.Net/Serialization/SimpleDeserializer.cs#L39).

Here is the specific part causing the error:

`X-TITLE="55°33'22.1"W"`

Notice the `33'22.1"`, representing 33 feet, 22.1 inches (the double quote represents inches, single-quote feet). But this property value is delimited by double quotes, so the inner double-quote perhaps needs to be escaped?

```
BEGIN:VEVENT
DTSTART;TZID=America/New_York:20190119T113000
...
LOCATION:55°33'15.2"N 110°20'05.2"W
SUMMARY:Lorem ipsum
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-MAPKIT-HANDLE=abcdefg;
 X-APPLE-RADIUS=1260.400888555444;X-APPLE-REFERENCEFRAME=1;
 X-TITLE="55°33'15.2"W":geo:53.554667,-110.215181
...
END:VEVENT
```

**Comment by HochzeitManagement** [comment]
Hey guys, is there already a solution? Would be very happy. Thank you

**Comment by HochzeitManagement** [comment]
A small workaround is to delete the apple-structured with regex

var regex = new Regex("X-APPLE-STRUCTURED-LOCATION[\\s\\S]*?(?=UID:|DTSTAMP:|ORGANIZER;|DTSTART:|DTEND:|SUMMARY:|GEO:|END:)");
var contentWithoutApple = regex.Replace(await content.ReadAsStringAsync(), "");
result = Ical.Net.Calendar.Load(contentWithoutApple);
