### ISSUE TITLE
Enums in capital case, not all upper case

### ISSUE THREAD

**Issue by mcshaz** [ical-org/ical.net#36]
First - huge thank you and kudos for getting this project under active development once again!

Setting the properties for an event instance, for example as below:

myEvt.Transparency = TransparencyType.Opaque;
myEvt.Status = EventStatus.Confirmed;

results in a serialised string with the following text:
STATUS:Confirmed
TRANSP:Opaque

this does not validate, as the string should be
STATUS:CONFIRMED
TRANSP:OPAQUE

**Comment by rianjs** [comment]
Thanks for the bug report. You seem comfortable making code changes... do you want to tackle this one?

If I had to guess, I would guess it's an easy-ish fix. Probably something like calling a `ToString` on an enum's name instead of using a `const string` inside a `TransparencyType` class. (Admittedly, I haven't looked.)

**Comment by mcshaz** [comment]
happy to - looking at the AttendeeSerializer class in its current form, the staus is not currently being serialized. I believe you might be working on this as per issue #45. ideally I can uncomment the tests in the deserialize test groups checking that these are failing, fix and rerun, but given the current problems with serialization it seems worth postponing issues to do with letter case until serialization of the properties is occurring.

Finding my way to the attendeeSerializer class, I saw a handful of simple/minor optimisations which are included in a pull request.

**Comment by mcshaz** [comment]
fixed d30880a42f43794d5274e90c9d04e918b134b238
