### ISSUE TITLE
Compile error in Wiki example code

### ISSUE THREAD

**Issue by mrgchr** [ical-org/ical.net#360]
Hello,

I found there are some errors on sample code in Wiki Home.
https://github.com/rianjs/ical.net/wiki

This
```cs
var e = new Event //Error
{
    Start = new CalDateTime(now),
    End = new CalDateTime(later),
    RecurrenceRules = new List<IRecurrencePattern> { rrule }, //Error
};
```
might be like following:
```cs
var e = new CalendarEvent
{
    Start = new CalDateTime(now),
    End = new CalDateTime(later),
    RecurrenceRules = new List<RecurrencePattern> { rrule },
};
```

Confirmed version:
Ical.Net 4.0.6

Regards.

**Comment by rianjs** [comment]
Yeah, that code works for v2, which is the most popular version of ical.net. (Not surprising, v3+ are .NetStandard, and a lot of devs don't know how to use .NetStandard libraries with .NET Framework applications, or can't because they're stuck on Framework < .NET 4.6.)

I haven't decided what I'm going to do about the docs yet.

**Comment by mrgchr** [comment]
Thanks for the quick reply.
