### ISSUE TITLE
V3 Breaking Changes - Renamed Event to CalendarEvent, etc.

### ISSUE THREAD

**Issue by rdeslonde** [ical-org/ical.net#365]
Hi @rianjs 

I just upgraded from ical.net v2 to v4 and there were breaking changes that I couldn't find any information about. It took a lot of digging to figure out that these are actually two separate versions, yet in the same code base.

I don't see any comments in the release notes about renaming Event to CalendarEvent etc. and all the examples in the github repo still use Event etc.

Did I miss something? Are all these changes documented somewhere obvious that I just missed? If not, maybe we should update this stuff? I'd be happy to do it as a small way I can contribute to this incredible library.

**Comment by rianjs** [comment]
Yeah there have been a few issues about documentation:

https://github.com/rianjs/ical.net/issues/360
https://github.com/rianjs/ical.net/issues/357

Jumping to v4 is a big change, no the least of which is because there's some pain when consuming .NET Standard libraries in Framework applications, especially if you havent' switched from `packages.config` to `PackageReference`s. This will need to be solved by Microsoft, and I know the .NetStandard team [is working on it](https://github.com/dotnet/standard/issues/481).

I wrote a migration page. It's pretty sparse: https://github.com/rianjs/ical.net/wiki/Migrating-from-earlier-versions-of-ical.net

The previous page about migrating from dday.ical might also be of some help: https://github.com/rianjs/ical.net/wiki/Migrating-from-dday.ical

**Comment by rdeslonde** [comment]
Thanks Rian, that migration page is definitely helpful. I wish I'd seen it before. I did already get it all working.

I didn't have too much trouble with the .net standard stuff...i think it was only the `System.Runtime.Serialization.Primitives` dependency that I had to individually add to my other projects. Other than that it all worked pretty smoothly.

Incidentally, just so you know, I made the choice to migrate solely for the Timezone serialization fix that you put in recently. It's absolutely necessary for exporting ical files to other calendar systems.

Thanks for all the work you've done and are doing for this great library.

**Comment by rianjs** [comment]
> I didn't have too much trouble with the .net standard stuff...i think it was only the System.Runtime.Serialization.Primitives dependency that I had to individually add to my other projects. Other than that it all worked pretty smoothly.

Yeah, the serialization primitives is an ongoing PITA that Microsoft will have to fix. In theory, it should "just work", but it doesn't. I think the "right" want to fix it is to enable [automatic binding redirects](https://github.com/dotnet/standard/issues/481). (Scroll down to the bottom of the first post.)
