### ISSUE TITLE
Breaks if NodaTime version is higher than 2.0.2.0

### ISSUE THREAD

**Issue by drewob** [ical-org/ical.net#402]
If NodaTime package version is > 2.0.2, I get this error:
System.IO.FileNotFoundException: Could not load file or assembly 'NodaTime, Version=2.0.2.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1' or one of its dependencies. The system cannot find the file specified.

The project is targeting .NET framework 4.7.1

**Comment by gregveres** [comment]
@drewob  I just ran into this as well when I upgraded from v2 of Ical.Net to v4 of Ical.Net. 

It turns out that the upgrade of v2 to either v3 or v4 deletes the reference to NodaTime altogether from your .csproj file. This is what then causes the error. 

There is either something wrong with the v2 NuGet files or there is something wrong with the v3 and v4 NuGet files. 

The fix was relatively easy - I did the upgrade with the package manager. Then I unloaded the projects from my solution, did a diff on the .csproj file and copied the deleted lines of nodatime from the previous version of the file to the new version of the file. 

I then reloaded the projects and everything worked fine. Since I was trying to go from v2 to v4, and this was happening, I decided I would get there piecemeal. So I first upgraded from v2 to the first available v3. This resulted in the NodaTime reference being dropped. I fixed that, then I was able to upgrade from the first v3 version to the latest v3 version without issue. (I had to fix my code to work with V3 since there are breaking changes, which was expected). Then I upgraded from latest v3 to v4.0.0 and again the upgrade worked and I had to fix more breaking changes in my code. I just finished upgrading to the latest v4.

I ran my unit tests and everything (except the PRODID setting) is working great. 

I assume you found your answer 28 days ago, but I figured I would leave a note for anybody else stumbling across this. 

BTW, I am using the latest v2.3.x version of NodaTime.

**Comment by yusrilmr** [comment]
In my case, I fixed it by giving this setting to my App.config : 
`<configuration>`
`  <runtime>`
`    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">`
`      <dependentAssembly>`
`        <assemblyIdentity name="NodaTime" publicKeyToken="4226afe0d9b296d1" culture="neutral" />`
`        <bindingRedirect oldVersion="0.0.0.0-2.3.0.0" newVersion="2.3.0.0" />`
`      </dependentAssembly>`
`    </assemblyBinding>`
`  </runtime>`
`</configuration>`

**Comment by mickeyjf** [comment]
I just updated my nuget NodaTime package to 2.4.7 and Npgsql.NodaTime to 4.0.10 from the immediately previous versions, and all references to NodaTime were removed from my .proj file. I was able to fix things by doing a diff with the old .csproj to discover that the references were in fact missing, and then manually updating the .proj. I am using Mono Develop 7.8.2, not VS.

**Comment by candicelj1708** [comment]
I am encountering this error using iCal.NET through PowerShell. I am trying to fumble my way through. Would anyone know off the top of their head where I might be able to apply a fix? The only thing I found that references NodaTime in the package files is the Ical.Net.deps.json file.

The error is triggered by: `$Calendar = [Ical.Net.Calendar]::Load($ICSCal)`

**Solution:**

Wanted to share the solution in case anyone was in a similar situation (using PowerShell). 

I had to download NodaTime and load the NodaTime assembly with PowerShell:

`[Reflection.Assembly]::LoadFile("C:\Assemblies\ical.net.4.1.11\lib\net46\Ical.Net.dll")
[Reflection.Assembly]::LoadFile("C:\Assemblies\nodatime.2.0.2\lib\net45\NodaTime.dll")`
