### ISSUE TITLE
A DtStart or DtEnd that is at midnight gets rendered as the "Value" format, but this is not spec compliant for UTC 

### ISSUE THREAD

**Issue by k290** [ical-org/ical.net#453]
If I have a CalendarEvent set up as follows:

new CalendarEvent
            {
                Start = new CalDateTime(start, "UTC"),
                End = new CalDateTime(end, "UTC"),
}

Where start or end is exactly at midnight then the ical will be rendered as:
DTEND;VALUE=DATE:20190731

However this is not spec compliant for UTC and causes meeting clients, such as Outlook to not convert this value from UTC to a local timezone.

This must be represented as:
DTEND:20190731T000000Z

When UTC is specified

**Comment by onebird100** [comment]
@k290 How did you work around this one? I'm currently facing this issue

**Comment by k290** [comment]
@onebird100   it was something like this:

I wrote a method to add/subtract(can't remember if it was add or subtract) one second (or maybe it was 1 millisecond) when its exactly midnight. Then the conversion will be fine, albeit off by one second. Email clients don't typically care about the seconds.

**Comment by arjan279** [comment]
Other workarounds which worked for me:

- explicitly set the event's AllDay property to false **after** setting both start and end date.
The start date and end date have a HasTime property which is automatically set to false when time is midnight. When false, it gets rendered without time. Setting AllDay=false will explicity set the HasTime flag to true for both the start and and date, and as a result, midnight time gets rendered. See https://github.com/rianjs/ical.net/blob/master/net-core/Ical.Net/CalendarComponents/CalendarEvent.cs#L120

- set the above HasTime property directly on the start date and end date instead of indirectly via the AllDay property of the event

**Comment by onebird100** [comment]
> @onebird100 it was something like this:
> 
> I wrote a method to add/subtract(can't remember if it was add or subtract) one second (or maybe it was 1 millisecond) when its exactly midnight. Then the conversion will be fine, albeit off by one second. Email clients don't typically care about the seconds.

Thank you. I ended up using this solution
